baseURL = "/"
languageCode = "en-us"
title = "Outlands Builds"
theme = "uo-outlands"

[params]
  description = "Builds, Guides, News, Events, Tips & Tricks for Ultima Online Outlands."
  author = "Outlands Builds"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
